version: '3.8'

services:
  ftp-server:
    image: fauria/vsftpd
    container_name: vsftpd
    environment:
      - FTP_USER=test_user
      - FTP_PASS=test_password
      - PASV_ADDRESS=127.0.0.1
      - PASV_MIN_PORT=21100
      - PASV_MAX_PORT=21110
    ports:
      - "20:20"
      - "21:21"
      - "21100-21110:21100-21110"
    volumes:
      - ftp_data:/home/vsftpd

  ftp-client:
    build:
      context: ./ftp-client
    container_name: ftp-client
    stdin_open: true
    tty: true
    depends_on:
      - ftp-server
    environment:
      - FTP_SERVER=ftp-server
      - FTP_ACTIVE_HOST=ftp-client
      - FTP_USER=test_user
      - FTP_PASS=test_password
volumes:
  ftp_data:
